version: '3.8' 

services:
  react-nginx-app:
    
    build:
      context: .
      dockerfile: Dockerfile
    ports:

      - "5173:80"
    environment:
    
       - CHOKIDAR_USEPOLLING=true
  
    restart: always