name: Render Spring POC HOOK

on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
